// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionFacturas_be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710223844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Invoice", b =>
                {
                    b.Property<int>("InvoiceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysToDue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceNumber");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Invoice", b =>
                {
                    b.OwnsMany("InvoiceCreditNote", "InvoiceCreditNote", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("CreditNoteAmount")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreditNoteDate")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CreditNoteNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("InvoiceId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("InvoiceId");

                            b1.ToTable("InvoiceCreditNote");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsMany("InvoiceDetail", "InvoiceDetail", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("InvoiceId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Subtotal")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("InvoiceId");

                            b1.ToTable("InvoiceDetail");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("Customer", "Customer", b1 =>
                        {
                            b1.Property<int>("InvoiceNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CustomerEmail")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CustomerName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CustomerRun")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InvoiceNumber");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceNumber");
                        });

                    b.OwnsOne("InvoicePayment", "InvoicePayment", b1 =>
                        {
                            b1.Property<int>("InvoiceNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime?>("PaymentDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PaymentMethod")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InvoiceNumber");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceNumber");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("InvoiceCreditNote");

                    b.Navigation("InvoiceDetail");

                    b.Navigation("InvoicePayment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
